services:
  postgres:
    image: 'postgres:latest'
    restart: always
    container_name: 'issuingbank'
    environment:
      - 'POSTGRES_DB=issuingbank'
      - 'POSTGRES_PASSWORD=lesson'
      - 'POSTGRES_USER=lesson'
    ports:
      - '5450:5432'
    volumes:
      - ./sql/create_schemas.sql:/docker-entrypoint-initdb.d/01_create_schemas.sql
      #- ./sql/init.sql:/docker-entrypoint-initdb.d/02_init.sql
#      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./sql/create_schemas.sql:/docker-entrypoint-initdb.d/create_schemas.sql
#      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      #       - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./src/main/resources/sql/create_schemas.sql:/docker-entrypoint-initdb.d/create_schemas.sql
      - ./issuingbank-data:/var/lib/postgresql/data
#      - ./initdb-issuingbank:/docker-entrypoint-initdb.d
#    command: >
#      bash -c "
#      psql -U lesson -d issuingbank -c 'CREATE SCHEMA IF NOT EXISTS issuingbankschema;
#      GRANT ALL PRIVILEGES ON SCHEMA issuingbankschema TO lesson;'
#      && exec docker-entrypoint.sh postgres
#      "

  redis:
    image: 'redis:latest'
    restart: always
    container_name: redis_cache_ib
    ports:
      - '6479:6379'
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin_issuingbank
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8070:80"
    volumes:
      - pgadmin_data_ib:/var/lib/pgadmin  #чтобы сохранялись настройки

      # Добавляем Swagger UI
  swagger-ui:
        image: swaggerapi/swagger-ui
        restart: always
        container_name: issuingbank-swagger-ui
        ports:
          - "8075:8080"
        environment:
          # Указываем URL вашего OpenAPI-документа (JSON/YAML)
          # Если API запущено локально (не в Docker) — используйте host.docker.internal
          SWAGGER_JSON: http://host.docker.internal:7050/v3/api-docs
          # это путь к апи сервиса
          # ИЛИ если API в этом же compose-файле — укажите имя сервиса:
          # SWAGGER_JSON: http://ваш_сервис_апи:порт/v3/api-docs
        depends_on:
          - postgres  # Зависит от Postgres (если API зависит от БД)
volumes:
  pgadmin_data_ib: #в конце — обязательны для определения pgadmin_data