databaseChangeLog:
  - changeSet:
      id: insert-account-default-values
      author: Vlad
      context: data
      preConditions:
        - tableExists:
            tableName: account
            schemaName: issuingbankschema
      changes:
        - sql:
            sql: |
              INSERT INTO issuingbankschema.account(account_number, balance, currency_id, account_type_id, client_id, account_opening_date, suspending_operations, account_closing_date)
              VALUES 
                ('40817810800000000001', 10.7, 1, 2, 1, '2022-10-21', false, NULL),
                ('40817810800000000002', 48.07, 1, 2, 2, '2022-04-05', false, NULL),
                ('40817810800000000003', 71.01, 1, 2, 2, '2022-10-20', false, NULL),
                ('40817810800000000004', 10.02, 2, 2, 1, '2022-10-21', false, NULL)
              ON CONFLICT (account_number) DO NOTHING;