databaseChangeLog:
  - changeSet:
      id: insert-default-card-values
      author: Vlad
      changes:
        - insert:
            schemaName: issuingbankschema
            tableName: card
            columns:
              - column: { name: card_number, value: 4123450000000019 }
              - column: { name: expiration_date, valueDate: 2025-12-31 }
              - column: { name: holder_name, value: IVAN I. IVANOV }
              - column: { name: card_status_id, valueNumeric: 2 }
              - column: { name: payment_system_id, valueNumeric: 1 }
              - column: { name: account_id, valueNumeric: 1 }
              - column: { name: client_id, valueNumeric: 1 }
              - column: { name: sent_to_processing_center, valueDate: 2022-10-21 }
              - column: { name: received_from_processing_center, valueDate: 2022-10-21 }

        - insert:
            schemaName: issuingbankschema
            tableName: card
            columns:
              - column: { name: card_number, value: 5123450000000024 }
              - column: { name: expiration_date, valueDate: 2025-12-31 }
              - column: { name: holder_name, value: SEMION E. PETROV }
              - column: { name: card_status_id, valueNumeric: 3 }
              - column: { name: payment_system_id, valueNumeric: 2 }
              - column: { name: account_id, valueNumeric: 2 }
              - column: { name: client_id, valueNumeric: 2 }
              - column: { name: sent_to_processing_center, valueDate: 2022-04-05 }
              - column: { name: received_from_processing_center, valueDate: 2022-04-05 }

        - insert:
            schemaName: issuingbankschema
            tableName: card
            columns:
              - column: { name: card_number, value: 3123450000000037 }
              - column: { name: expiration_date, valueDate: 2025-10-31 }
              - column: { name: holder_name, value: DMITRY S. SIDOROV }
              - column: { name: card_status_id, valueNumeric: 2 }
              - column: { name: payment_system_id, valueNumeric: 3 }
              - column: { name: account_id, valueNumeric: 3 }
              - column: { name: client_id, valueNumeric: 3 }
              - column: { name: sent_to_processing_center, valueDate: 2022-10-20 }
              - column: { name: received_from_processing_center, valueDate: 2022-10-20 }

        - insert:
            schemaName: issuingbankschema
            tableName: card
            columns:
              - column: { name: card_number, value: 4123450000000043 }
              - column: { name: expiration_date, valueDate: 2025-12-31 }
              - column: { name: holder_name, value: IVAN I. IVANOV }
              - column: { name: card_status_id, valueNumeric: 2 }
              - column: { name: payment_system_id, valueNumeric: 1 }
              - column: { name: account_id, valueNumeric: 4 }
              - column: { name: client_id, valueNumeric: 1 }
              - column: { name: sent_to_processing_center, valueDate: 2022-10-21 }
              - column: { name: received_from_processing_center, valueDate: 2022-10-21 }
